---
- name: Create two EC2 nodes
  gather_facts: False
  hosts: localhost
  
  tasks:

  - name: Ensure that two hosts exists
    ec2:
      region: eu-central-1
      instance_type: t2.micro
      image: "ami-0767046d1677be5a0"
      wait: true
      exact_count: 2
      count_tag:
        Name: Lesson13
      instance_tags:
        Name: Lesson13
    register: ec2