---
- name: Build Java App
  gather_facts: False
  hosts: localhost
  remote_user: ubuntu
  vars:
    keypair: lesson13_key_maven
    ansible_key: /tmp/lesson13_keypair_maven.pem
    instance_type: t2.micro
    image: "ami-0767046d1677be5a0"
    security_group: lesson13-maven-securitygroup
    region: eu-central-1
  
  tasks:

  - name: Create a new ec2 key pair
    ec2_key:
      region: "{{ region }}"
      name: "{{ keypair }}"
    register: ec2_key_result

  - name: Save private key
    copy: content="{{ ec2_key_result.key.private_key }}" dest="/tmp/lesson13_keypair_maven.pem" mode=0600
    when: ec2_key_result.changed

  - name: Ensure that this security group is present
    ec2_group:
      name: "{{ security_group }}"
      description: Security Group for Lesson13
      region: "{{ region }}"
      rules:
        - proto: tcp
          ports:
          - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow ssh access

  - name: Ensure that Maven host is present
    ec2:
      key_name: "{{ keypair }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      group: "{{ security_group }}"
      image: "{{ image }}"
      wait: true
      exact_count: 1
      count_tag:
        Name: Lesson13-Maven
      instance_tags:
        Name: Lesson13-Maven
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: lesson13-maven
      ansible_ssh_private_key_file: "{{ ansible_key }}"
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_ip }}"
    wait_for_connection:
      delay: 30
      timeout: 30
    loop: "{{ ec2.instances }}"

- name: Install Maven
  hosts: lesson13-maven
  remote_user: ubuntu
  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    ansible_key: /tmp/lesson13_keypair_maven.pem
  become: True
  gather_facts: True

  tasks:

  - name: Ensure openJDK is present
    apt:
      name: default-jdk
      update_cache: yes
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present

  - name: Ensure pip is present
    apt:
      name: python3-pip
      state: present

  - name: Install boto3 and botocore with pip3 module
    pip:
      name: 
      - boto3
      - botocore

  - name: Get java application
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
      clone: yes
      dest: /tmp/boxfuse-sample-java-war-hello

  - name: Build java application
    shell: mvn package
    args:
      chdir: /tmp/boxfuse-sample-java-war-hello

  - name: Create an empty bucket
    aws_s3:
      bucket: lesson13-bucket
      region: eu-central-1
      mode: create
      permission: public-read

  - name: Copy artefact to bucket
    aws_s3:
      bucket: lesson13-bucket
      object: hello-1.0.war
      src: /tmp/boxfuse-sample-java-war-hello/hello-1.0.war
      mode: put
         
- name: Deploy Java App
  gather_facts: False
  hosts: localhost
  remote_user: ubuntu
  vars:
    keypair: lesson13_key_tomcat
    ansible_key: /tmp/lesson13_keypair_tomcat.pem
    instance_type: t2.micro
    image: "ami-0767046d1677be5a0"
    security_group: lesson13-tomcat-securitygroup
    region: eu-central-1
  
  tasks:

  - name: Create a new ec2 key pair
    ec2_key:
      region: "{{ region }}"
      name: "{{ keypair }}"
    register: ec2_key_result

  - name: Save private key
    copy: content="{{ ec2_key_result.key.private_key }}" dest="/tmp/lesson13_keypair_tomcat.pem" mode=0600
    when: ec2_key_result.changed

  - name: Ensure that this security group is present
    ec2_group:
      name: "{{ security_group }}"
      description: Security Group for Lesson13
      region: "{{ region }}"
      rules:
        - proto: tcp
          ports:
          - 22
          - 8080
          cidr_ip: 0.0.0.0/0
          rule_desc: allow ssh and tomcat access

  - name: Ensure that Tomcat host is present
    ec2:
      key_name: "{{ keypair }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      group: "{{ security_group }}"
      image: "{{ image }}"
      wait: true
      exact_count: 1
      count_tag:
        Name: Lesson13-Tomcat
      instance_tags:
        Name: Lesson13-Tomcat
    register: ec2
  
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: lesson13-tomcat
      ansible_ssh_private_key_file: "{{ ansible_key }}"
    loop: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_ip }}"
    wait_for_connection:
      delay: 30
      timeout: 30
    loop: "{{ ec2.instances }}"

- name: Install Tomcat
  hosts: lesson13-tomcat
  remote_user: ubuntu
  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  become: True
  gather_facts: True

  tasks:

  - name: Ensure Tomcat is present
    apt:
      name: tomcat9
      update_cache: yes
      state: present

  - name: Ensure tomcat service is running
    service:
      name: tomcat9
      state: started

  - name: Ensure pip is present
    apt:
      name: python3-pip
      state: present

  - name: Install boto3 and botocore with pip3 module
    pip:
      name: 
      - boto3
      - botocore

  - name: Create an empty bucket
    aws_s3:
      bucket: lesson13-bucket
      region: eu-central-1
      mode: create
      permission: public-read

  - name: Download artefact to romcat webroot
    aws_s3:
      bucket: lesson13-bucket
      region: eu-central-1
      object: hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello-1.0.war
      mode: get



  
  
  

  

  

